name: deploy

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.3
      - name: Build
        run: deno run --allow-read --allow-write https://raw.githubusercontent.com/olaven/markblog/master/mod.ts build
      - name: merge master -> publish
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: publish
          github_token: ${{ github.token }}
