name: deploy

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # i.e. fetch entire history, ref. https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.25.3
      - name: Build
        run: deno run --allow-read --allow-write --allow-run --unstable https://raw.githubusercontent.com/olaven/markblog/v0.1.0/mod.ts build
      - name: merge master -> publish
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: publish
          github_token: ${{ github.token }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: publish
          FOLDER: . # The folder the action should deploy.
