name: deploy

on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.6.3
      - name: Build
        run: deno run --allow-read --allow-write https://raw.githubusercontent.com/olaven/markblog/master/mod.ts build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: publish
          FOLDER: . # The folder the action should deploy.
