name: deploy

on:
    push:
        branches: [publish]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: denolib/setup-deno@master
            with:
              deno-version: 0.36
          - name: Build
            run: deno --allow-read --allow-write run https://raw.githubusercontent.com/olaven/markblog/master/markblog.ts --options options.json 
          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v3
            with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: master 
                FOLDER: . # The folder the action should deploy.