name: deploy

on:
    push:
        branches: [publish]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - uses: denolib/setup-deno@master
            with:
              deno-version: 0.36
          - name: Install markblog 
            run: deno install --allow-read --allow-write markblog https://raw.githubusercontent.com/olaven/markblog/master/markblog.ts && export PATH="/home/runner/.deno/bin:$PATH"
          - name: Build
            run: markblog build --options options.json
          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v3
            with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BRANCH: master 
                FOLDER: . # The folder the action should deploy.